### ISSUE TITLE
No Chrome environment, please install Chrome 59+! 

### ISSUE THREAD

**Issue by GavinFreedom** [Binaryify/express-middleware-seo#3]
I already have chrome installed on the server
[root@izj6c1h8vqjcmblprak6fvz chrome-render]# chrome --version
Google Chrome 66.0.3359.117

However, when the project is running, it prompts
Error: chrome-render timeout
at Object. (/data/www/novel-nodeServer/node_modules/chrome-render/index.js:6:28)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object. (/data/www/novel-nodeServer/node_modules/express-middleware-seo/core.js:2:22)
at Module._compile (module.js:652:30)
No Chrome environment, please install Chrome 59+!

How can I solve it?

**Comment by Binaryify** [comment]
try this
`export CHROME_SOURCE_URL=http://dl.google.com/dl/linux/direct/google-chrome-stable_current_amd64.deb`
`wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL`
